spring.application.name=ws-endpoint

spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl

spring.data.redis.host=localhost
spring.data.redis.port=6379

app.users[0].username=user0
app.users[0].password=pass0
app.users[1].username=user1
app.users[1].password=pass1
app.users[2].username=user2
app.users[2].password=pass2

spring.session.data.redis.repository-type=indexed

app.ws.allowedOrigins=http://localhost:8080
app.ws.brokerURL=ws://localhost:8080/api/ws-endpoint
app.ws.heartbeatIncoming=PT10S
app.ws.heartbeatOutgoing=PT10S
app.ws.reconnectDelay=PT5S
app.ws.presenceTtl=PT2M
app.ws.refreshInterval=PT90S

app.pubsub.namespace=local
app.pubsub.instance=instance1
